### ISSUE TITLE
Use the new computation API

### ISSUE THREAD

**Issue by MattiSG** [openfisca/demonstrator#3]
As defined in openfisca/openfisca-core#520, a new, simpler computation endpoint is to be produced.
The demonstrator should be the first consumer of this endpoint.

**Comment by MattiSG** [comment]
- Runs on OpenFisca-France.
- May simply adapt the current codebase.
- May be a rewrite, in which case we should focus on testing the API rather than providing a great UX. Managing several individuals is a must to test entity management. The example should stay the same, but the output may be a simple table rather than a graph, to minimise the time spent on UX.

**Comment by Anna-Livia** [comment]
WIP - JS/HTML version of the demonstrator with old endpoints :

https://github.com/openfisca/demonstrator/tree/demonstrator_for_new_endpoint

**Comment by MattiSG** [comment]
- Work directly in the OpenFisca website, on a `/demo` page.
- Remove as much text as possible.
- Specify which country package and country package version is used.
- Ensure a valid result is shown on load.
- Merge visualisation and legend.

**Comment by MattiSG** [comment]
- Add to the `www.openfisca.fr` front page.

**Comment by benjello** [comment]
May bring the decomposition subject up. it may be the right time (but not the right place) to discuss of an appropriate format for those.

**Comment by fpagnoux** [comment]
> May I bring the decomposition subject up. it may be the right time (but not the right place) to discuss of an appropriate format for those.

Decomposing the disposable income is part of the demonstrator. Implementing it in this specific case will help us understand better decompositions, and give us a more enlightened opinion.

But you can already open an issue about decompositions 🙂.

**Comment by fpagnoux** [comment]
I adapted the current demonstrator to make it work with the new API. Here is my comments:

- The adaptation work was not significant. Our new API is not _that_ different from the former one.

- Declaring a single household is slightly more heavy than before. I found it unnatural to write:
```JS
foyers_fiscaux: {
    foyer_fiscal: {
      declarants: ["individu0", "individu1"],
    }
},
```
With the previous API, this would have been:
```JS
foyers_fiscaux: [
    {
      declarants: ["individu0", "individu1"],
    }
],
```
which is a little simpler as I don't need to give an arbitrary name to my unique household.

As an API client, I would have liked to write:
```JS
foyer_fiscal: {
      declarants: ["individu0", "individu1"],
},
```
This sounds technically doable (we have the plural and singular of entities name), but not sure about whether it's a good idea and when it should be prioritized.

Anyway, as unnatural as it was, it didn't cost much to add the extra level of nesting.

**Comment by fpagnoux** [comment]
- Some error messages contain `"`, which makes it harder to read when debugging.
For instance:
```JS
"date_naissance": "Invalid type: must be of type object. Input variables must be set for specific periods. For instance: {\"salary\": {\"2017-01\": 2000, \"2017-02\": 2500}}"
```

- There is a bug for unique roles, which don't have a plural set because only one should exist in a given entity (for instance `personne_de_reference` in `menages`). This can be fixed easily.

- The former json parser does [extra assumptions](https://github.com/openfisca/openfisca-france/blob/18.5.2/openfisca_france/scenarios.py#L444), that the new API doesn't do. For instance, if two people are set as `declarants` in a `foyer_fiscal`, their `staut_marital` is [set to `pacsé` by default](https://github.com/openfisca/openfisca-france/blob/18.5.2/openfisca_france/scenarios.py#L484). Consequently, the same request may give different results on the new and legacy `calculate` route. The client of the new API must specify more information than with the legacy one. For instance, in our demonstrator, he must [specify that the `statut_marital ` of each menage member is `pacsé`](https://github.com/openfisca/demonstrator/blob/demonstrator_for_new_endpoint/demonstrator.html#L47).

**Comment by MattiSG** [comment]
Great, thanks a lot for this experience report!

Arbitrary, non-significant yet mandatory names could be recommended as `_`, as in most functional languages conventions taking indexed parameters. Seems to early for that though.

> Some error messages contain ", which makes it harder to read when debugging.

This is annoying, as it means no copy-paste of suggested fixes… I don't know how to fix this, as removing the quotes would also prevent copy-paste, and could be even more confusing to users that are not so at ease with JSON (“this is valid JS, is suggested, but is refused by the API?!”).

> don't have a plural set because only one should exist in a given entity

I don't know what's the simplest, but I would also be ok with always setting the `plural` key, duplicating the singular for unique roles.

> Should the new API offer the possibility to country packages developers to add such a custom input processing[, or] should we consider it as a bad practise?

This specific discussion has been moved to https://github.com/openfisca/openfisca-core/issues/540.

> I adapted the current demonstrator to make it work with the new API.

Is it still relevant to deliver & maintain a pure HTML version then?

**Comment by fpagnoux** [comment]
> Is it still relevant to deliver & maintain a pure HTML version then?

Sorry, by current demonstrator I meant the one built by @Anna-Livia :laughing:
